#ifndef KL_IFACE_COMMON_H
#define KL_IFACE_COMMON_H

#include "ipc/ipc_sock_common.h"

enum
{
    CLIENT_CALL_SEARCH_KEY_WORD = ipc::CLIENT_CALL_Method_Base,
    CLIENT_CALL_PLAY_SEARCH_NAME,
    CLIENT_CALL_PLAY_SEARCH_INDEX,
    CLIENT_CALL_PLAY_PAUSE,
    CLIENT_CALL_PLAY_PLAYING,
    CLIENT_CALL_PLAY_NEXT,
    CLIENT_CALL_PLAY_PREV,
};

enum
{
    SERVICE_NOTIFY_SEARCH_RESULT   = ipc::SERVICE_NOTIFY_Method_Base,

};

#endif // KL_IFACE_COMMON_H
